name: Deploy Documentation

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Rustup
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable

            - name: Build
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release --all-features
