name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps

      - name: Prepare Documentation
        run: |
          mkdir -p docs
          cp -r target/doc/* docs/
          echo '<meta http-equiv="refresh" content="0; URL=gsync">' > docs/index.html

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
